
const CODE_HASH='47a0115327e38259eff6308abff2dc76975777095b581cc163b50b6809250ae0';
const CLOUD_URI='/api/data';
const LEGACY_KEY='travel-vault-live-v1';
const LOCAL_CACHE='travel-vault-cloud-cache-v2';
const EMPTY=()=>({version:2,rev:0,trip:{_updatedAt:0},flights:[],hotels:[],plans:[],transport:[],_deleted:{},finalizedAt:0,updatedAt:0});
let data=EMPTY(),cryptoKey=null,failedAttempts=0,lockedUntil=0,saving=false,lastCloudStamp=0,toastTimer=null,currentAddType='plans',currentListType='plans';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function now(){return Date.now()}
function uid(){return crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now().toString(36)}
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function numberValue(value){const n=Number(value);return Number.isFinite(n)&&n>0?Math.round(n):0}
function yen(value){return '¥'+numberValue(value).toLocaleString('ja-JP')}
function formatDateTime(value){return value?new Date(value).toLocaleString('zh-HK',{month:'short',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'}):'—'}
function timeOnly(value){return value?new Date(value).toLocaleTimeString('zh-HK',{hour:'2-digit',minute:'2-digit'}):'—'}
function dateKey(value){return value?String(value).slice(0,10):'未定日期'}
function typeLabel(type){return({flights:'航班',hotels:'酒店',plans:'景點行程',transport:'交通'})[type]||type}
function typeIcon(type){return({flights:'✈️',hotels:'🏨',plans:'📍',transport:'🚆'})[type]||'•'}
function showToast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
function setSync(type,text){$('#syncDot').className='sync-dot '+(type||'');$('#syncText').textContent=text}
function toggleCode(){const input=$('#code');input.type=input.type==='password'?'text':'password'}
async function sha256(text){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('')}
async function deriveKey(code){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(code),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:new TextEncoder().encode('travel-vault-shared-2026'),iterations:180000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function toBase64(bytes){return btoa(String.fromCharCode(...bytes))}
function fromBase64(text){return Uint8Array.from(atob(text),ch=>ch.charCodeAt(0))}
async function encryptData(value){const iv=crypto.getRandomValues(new Uint8Array(12));const raw=new TextEncoder().encode(JSON.stringify(value));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},cryptoKey,raw);return{v:2,iv:toBase64(iv),cipher:toBase64(new Uint8Array(cipher)),updatedAt:value.updatedAt||now()}}
async function decryptData(envelope){if(!envelope||!envelope.iv||!envelope.cipher)return null;const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromBase64(envelope.iv)},cryptoKey,fromBase64(envelope.cipher));return JSON.parse(new TextDecoder().decode(raw))}
function normalize(value){const result=Object.assign(EMPTY(),value||{});['flights','hotels','plans','transport'].forEach(key=>result[key]=Array.isArray(result[key])?result[key]:[]);result._deleted=result._deleted||{};result.trip=result.trip||{_updatedAt:0};return result}
function mergeArray(a=[],b=[],deleted={}){const map=new Map();[...a,...b].forEach(item=>{if(!item?.id)return;const old=map.get(item.id);if(!old||Number(item._updatedAt||0)>=Number(old._updatedAt||0))map.set(item.id,item)});return[...map.values()].filter(item=>Number(deleted[item.id]||0)<Number(item._updatedAt||0))}
function mergeData(a,b){a=normalize(a);b=normalize(b);const deleted={...a._deleted};Object.entries(b._deleted||{}).forEach(([key,value])=>deleted[key]=Math.max(Number(deleted[key]||0),Number(value||0)));const out=EMPTY();out._deleted=deleted;out.trip=Number(a.trip?._updatedAt||0)>=Number(b.trip?._updatedAt||0)?a.trip:b.trip;['flights','hotels','plans','transport'].forEach(key=>out[key]=mergeArray(a[key],b[key],deleted));out.finalizedAt=Math.max(Number(a.finalizedAt||0),Number(b.finalizedAt||0));out.rev=Math.max(Number(a.rev||0),Number(b.rev||0));out.updatedAt=Math.max(Number(a.updatedAt||0),Number(b.updatedAt||0));return out}
function saveCache(){localStorage.setItem(LOCAL_CACHE,JSON.stringify(data))}
function loadCache(){try{return normalize(JSON.parse(localStorage.getItem(LOCAL_CACHE)))}catch{return EMPTY()}}
async function cloudRead(){const response=await fetch(CLOUD_URI+'?t='+Date.now(),{cache:'no-store',headers:{'X-Travel-Key':CODE_HASH}});if(response.status===404)return null;if(!response.ok)throw new Error('讀取雲端失敗');return decryptData(await response.json())}
async function cloudWrite(value){const envelope=await encryptData(value);const response=await fetch(CLOUD_URI,{method:'PUT',headers:{'Content-Type':'application/json','X-Travel-Key':CODE_HASH},body:JSON.stringify(envelope)});if(!response.ok)throw new Error('寫入雲端失敗')}
async function initializeCloud(){let local=loadCache();try{const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');if(legacy)local=mergeData(local,normalize(legacy))}catch{}local.updatedAt=now();local.rev=1;await cloudWrite(local);return local}
async function unlock(){const codeInput=$('#code'),error=$('#loginError');if(now()<lockedUntil){error.textContent='請稍後再試';return}const code=codeInput.value;if(await sha256(code)!==CODE_HASH){failedAttempts++;codeInput.value='';error.textContent='驗證碼不正確';if(failedAttempts>=5){lockedUntil=now()+30000;failedAttempts=0;error.textContent='錯誤次數過多，已暫停 30 秒'}return}error.textContent='';setSync('','連接雲端');cryptoKey=await deriveKey(code);try{let remote=await cloudRead();if(!remote)remote=await initializeCloud();data=mergeData(loadCache(),remote);lastCloudStamp=Number(remote.updatedAt||0);saveCache();setSync('ok','已同步')}catch(err){console.error(err);data=loadCache();setSync('bad','離線模式');showToast('雲端暫時未能連接，已開啟本機資料')}sessionStorage.setItem('tv-ok','1');sessionStorage.setItem('tv-code',code);$('#lock').classList.add('hidden');codeInput.value='';render()}
function lockNow(){sessionStorage.removeItem('tv-ok');sessionStorage.removeItem('tv-code');cryptoKey=null;$('#lock').classList.remove('hidden');$('#code').focus()}
async function resumeSession(){const code=sessionStorage.getItem('tv-code');if(sessionStorage.getItem('tv-ok')==='1'&&code){cryptoKey=await deriveKey(code);data=loadCache();$('#lock').classList.add('hidden');render();syncNow(false)}}
async function commit(){if(!cryptoKey)return;data.updatedAt=now();data.rev=Number(data.rev||0)+1;saveCache();render();if(saving)return;saving=true;setSync('','儲存中');try{const remote=await cloudRead();if(remote)data=mergeData(data,remote);data.updatedAt=now();data.rev=Math.max(Number(data.rev||0),Number(remote?.rev||0))+1;await cloudWrite(data);lastCloudStamp=data.updatedAt;saveCache();setSync('ok','已同步');showToast('已儲存並同步')}catch(err){console.error(err);setSync('bad','稍後重試');showToast('已保存於本機，稍後再同步')}finally{saving=false}}
async function syncNow(showMessage){if(!cryptoKey||saving)return;setSync('','同步中');try{const remote=await cloudRead();if(remote){data=mergeData(data,remote);lastCloudStamp=Number(remote.updatedAt||0);saveCache();render()}setSync('ok','已同步');if(showMessage)showToast('已取得最新資料')}catch(err){console.error(err);setSync('bad','同步失敗');if(showMessage)showToast('暫時未能同步')}}
function formObject(form){return Object.fromEntries(new FormData(form).entries())}
function saveTrip(event){event.preventDefault();const value=formObject(event.currentTarget);value._updatedAt=now();data.trip=value;commit()}
function setAddType(type){currentAddType=type;const form=$('#addForm');form.elements.entryType.value=type;$$('#addTabs button').forEach(b=>b.classList.toggle('active',b.dataset.add===type));const cfg={plans:{title:'景點／活動名稱',placeholder:'例如：太宰府天滿宮',extra:'類別',options:['景點','餐廳','購物','活動'],start:'開始時間',end:'結束時間',cost:'行程金額（円）',submit:'新增景點行程',location:true,route:false},transport:{title:'路線／班次',placeholder:'例如：機場線／巴士 A1',extra:'交通工具',options:['鐵路','巴士','步行','的士','自駕','渡輪'],start:'出發時間',end:'抵達時間',cost:'交通金額（円）',submit:'新增交通',location:false,route:true},flights:{title:'航班編號',placeholder:'例如：CX588',extra:'航空公司',options:null,start:'起飛時間',end:'抵達時間',cost:'機票金額（円）',submit:'新增航班',location:false,route:true},hotels:{title:'酒店名稱',placeholder:'例如：博多站前酒店',extra:null,options:null,start:'入住時間',end:'退房時間',cost:'住宿金額（円）',submit:'新增酒店',location:true,route:false}}[type];$('#titleLabel').textContent=cfg.title;form.elements.title.placeholder=cfg.placeholder;$('#startLabel').textContent=cfg.start;$('#endLabel').textContent=cfg.end;$('#costLabel').textContent=cfg.cost;$('#addSubmit').textContent=cfg.submit;$('#locationField').classList.toggle('hidden',!cfg.location);$('#fromField').classList.toggle('hidden',!cfg.route);$('#toField').classList.toggle('hidden',!cfg.route);$('#extraField').classList.toggle('hidden',!cfg.extra);if(cfg.extra){$('#extraLabel').textContent=cfg.extra;const old=form.elements.extra.value;if(cfg.options){const select=document.createElement('select');select.name='extra';select.id='extraInput';select.innerHTML=cfg.options.map(x=>`<option>${x}</option>`).join('');$('#extraInput').replaceWith(select)}else{const input=document.createElement('input');input.name='extra';input.id='extraInput';input.placeholder='例如：國泰航空';$('#extraInput').replaceWith(input)}}if(type==='hotels')form.elements.location.placeholder='酒店地址';['from','to'].forEach(name=>{form.elements[name].required=cfg.route});form.elements.location.required=false}
function addEntry(event){event.preventDefault();const form=event.currentTarget,type=form.elements.entryType.value,value=formObject(form);value.id=uid();delete value.entryType;value.costYen=numberValue(value.costYen);value._updatedAt=now();data[type].push(value);form.reset();setAddType(type);commit();goPage('timeline');currentListType=type;renderCategoryList();showToast(typeLabel(type)+'已加入')}
function deleteEntry(type,id){if(!confirm('確定刪除這個安排？'))return;data[type]=data[type].filter(item=>item.id!==id);data._deleted[id]=now();commit()}
function openRoute(from,to,mode){const travelMode=mode==='步行'?'walking':mode==='自駕'||mode==='的士'?'driving':'transit';open('https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(from||'')+'&destination='+encodeURIComponent(to||'')+'&travelmode='+travelMode,'_blank')}
function allEntries(){return['flights','hotels','plans','transport'].flatMap(type=>data[type].map(item=>({...item,_type:type}))).sort((a,b)=>new Date(a.start||0)-new Date(b.start||0))}
function costByType(type){return data[type].reduce((sum,item)=>sum+numberValue(item.costYen),0)}
function totalCost(){return['flights','hotels','plans','transport'].reduce((sum,type)=>sum+costByType(type),0)}
function totalItems(){return allEntries().length}
function itemLocation(item){return item.location||[item.from,item.to].filter(Boolean).join(' → ')}
function itemCard(item,type){const mapButton=type==='transport'||type==='flights'?`<button class="btn soft" type="button" onclick='openRoute(${JSON.stringify(item.from||'')},${JSON.stringify(item.to||'')},${JSON.stringify(item.extra||'')})'>開啟路線</button>`:item.location?`<button class="btn soft" type="button" onclick="open('https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(item.location)}','_blank')">開啟地圖</button>`:'';return`<article class="item" data-type="${type}"><div class="item-head"><div class="item-title">${escapeHtml(item.title||'未命名')}</div><span class="badge">${typeIcon(type)} ${escapeHtml(item.extra||typeLabel(type))}</span></div><div class="item-time">${formatDateTime(item.start)}${item.end?' → '+formatDateTime(item.end):''}</div>${itemLocation(item)?`<div class="meta">📍 ${escapeHtml(itemLocation(item))}</div>`:''}${item.notes?`<div class="meta">${escapeHtml(item.notes)}</div>`:''}${numberValue(item.costYen)?`<div class="cost">${yen(item.costYen)}</div>`:''}<div class="item-actions">${mapButton}<button class="btn danger" type="button" onclick="deleteEntry('${type}','${item.id}')">刪除</button></div></article>`}
function timelineData(){const out={};allEntries().forEach(item=>{const day=dateKey(item.start);(out[day]??=[]).push(item)});return out}
function renderTimeline(){const el=$('#timelineView'),days=timelineData(),keys=Object.keys(days).sort();if(!keys.length){el.innerHTML='<div class="empty">尚未加入行程。前往「新增」加入第一個安排。</div>';return}el.innerHTML=keys.map(day=>{const dateLabel=day==='未定日期'?day:new Date(day+'T12:00:00').toLocaleDateString('zh-HK',{month:'long',day:'numeric',weekday:'long'});return`<section class="day-block"><div class="day-title"><h3>${escapeHtml(dateLabel)}</h3><span>${days[day].length} 項安排</span></div>${days[day].map(item=>`<div class="time-row"><div class="time-col">${timeOnly(item.start)}</div><div class="line-col"></div><div><div class="event-title">${typeIcon(item._type)} ${escapeHtml(item.title||'未命名')}</div><div class="event-meta">${escapeHtml(itemLocation(item)||typeLabel(item._type))}${item.end?'・至 '+timeOnly(item.end):''}${numberValue(item.costYen)?'・'+yen(item.costYen):''}</div></div></div>`).join('')}</section>`}).join('')}
function renderCategoryList(){const list=$('#categoryList');$$('#listTabs button').forEach(b=>b.classList.toggle('active',b.dataset.list===currentListType));list.innerHTML=data[currentListType].length?data[currentListType].slice().sort((a,b)=>new Date(a.start||0)-new Date(b.start||0)).map(item=>itemCard(item,currentListType)).join(''):'<div class="empty">此分類尚未有資料。</div>'}
function nextEntry(){const current=Date.now(),future=allEntries().filter(item=>item.start&&new Date(item.start).getTime()>=current);return future[0]||allEntries()[0]||null}
function tripDays(){const start=data.trip?.start,end=data.trip?.end;if(!start||!end)return '—';return Math.max(1,Math.round((new Date(end+'T12:00:00')-new Date(start+'T12:00:00'))/86400000)+1)+' 日'}
function renderBudget(){$('#budgetTotal').textContent=yen(totalCost());['flights','hotels','plans','transport'].forEach(type=>$('#cost'+type[0].toUpperCase()+type.slice(1)).textContent=yen(costByType(type)));const items=allEntries().filter(x=>numberValue(x.costYen)>0).sort((a,b)=>numberValue(b.costYen)-numberValue(a.costYen));$('#budgetItems').innerHTML=items.length?items.map(item=>`<article class="item" data-type="${item._type}"><div class="item-head"><div class="item-title">${typeIcon(item._type)} ${escapeHtml(item.title)}</div><div class="cost">${yen(item.costYen)}</div></div><div class="meta">${typeLabel(item._type)}・${formatDateTime(item.start)}</div></article>`).join(''):'<div class="empty">尚未輸入任何金額。</div>'}
function renderFinal(){const container=$('#finalPreview'),trip=data.trip||{},days=timelineData(),keys=Object.keys(days).sort();let html=`<div class="final-cover"><div class="eyebrow">COMPLETE ITINERARY</div><h2>${escapeHtml(trip.name||'我的旅程')}</h2><div class="meta">${escapeHtml(trip.destination||'')}${trip.start?'・'+escapeHtml(trip.start)+' 至 '+escapeHtml(trip.end||'未定'):''}</div><div class="final-cost">${yen(totalCost())}</div></div>`;if(!keys.length)html+='<div class="empty" style="margin-top:12px">尚未加入任何行程。</div>';else html+=`<div class="timeline" style="margin-top:12px">${keys.map(day=>{const label=day==='未定日期'?day:new Date(day+'T12:00:00').toLocaleDateString('zh-HK',{month:'long',day:'numeric',weekday:'long'});return`<section class="day-block"><div class="day-title"><h3>${escapeHtml(label)}</h3><span>${days[day].length} 項</span></div>${days[day].map(item=>`<div class="time-row"><div class="time-col">${timeOnly(item.start)}</div><div class="line-col"></div><div><div class="event-title">${typeIcon(item._type)} ${escapeHtml(item.title||'未命名')}</div><div class="event-meta">${escapeHtml(itemLocation(item)||typeLabel(item._type))}${numberValue(item.costYen)?'・'+yen(item.costYen):''}</div></div></div>`).join('')}</section>`}).join('')}</div>`;container.innerHTML=html;$('#finalStatus').textContent=data.finalizedAt?'上次完成：'+new Date(data.finalizedAt).toLocaleString('zh-HK'):'尚未標記完成'}
function render(){const trip=data.trip||{},form=$('#tripForm');['name','destination','start','end','notes'].forEach(key=>form.elements[key].value=trip[key]||'');$('#heroName').textContent=trip.name||'尚未設定旅程';$('#heroMeta').textContent=trip.start?`${trip.start} 至 ${trip.end||'未定'}・${trip.destination||''}`:'加入目的地和旅行日期，開始安排你的旅程。';$('#brandTrip').textContent=trip.name||'私人共享旅程規劃';$('#statDays').textContent=tripDays();$('#statCost').textContent=yen(totalCost());const next=nextEntry();$('#nextTitle').textContent=next?`${typeIcon(next._type)} ${next.title}`:'尚未加入安排';$('#nextMeta').textContent=next?`${formatDateTime(next.start)}${itemLocation(next)?'・'+itemLocation(next):''}`:'前往「新增」開始規劃';renderTimeline();renderCategoryList();renderBudget();renderFinal()}
function goPage(page,addType){$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$$('.page').forEach(p=>p.classList.toggle('active',p.id===page));if(addType)setAddType(addType);if(page==='timeline')renderTimeline();if(page==='budget')renderBudget();if(page==='final')renderFinal();scrollTo({top:0,behavior:'smooth'})}
function finalizeTrip(){if(!totalItems()){showToast('請先加入行程資料');return}data.finalizedAt=now();commit();renderFinal();showToast('完整行程已製作完成')}
function finalDocument(){const trip=data.trip||{},days=timelineData(),keys=Object.keys(days).sort();const sections=keys.map(day=>{const label=day==='未定日期'?day:new Date(day+'T12:00:00').toLocaleDateString('zh-HK',{year:'numeric',month:'long',day:'numeric',weekday:'long'});return`<section><h2>${escapeHtml(label)}</h2>${days[day].map(item=>`<article><div class="line"><strong>${typeIcon(item._type)} ${escapeHtml(item.title)}</strong><span>${escapeHtml(typeLabel(item._type))}</span></div><div>${formatDateTime(item.start)}${item.end?' → '+formatDateTime(item.end):''}</div>${itemLocation(item)?`<div>📍 ${escapeHtml(itemLocation(item))}</div>`:''}${numberValue(item.costYen)?`<div class="money">${yen(item.costYen)}</div>`:''}${item.notes?`<p>${escapeHtml(item.notes)}</p>`:''}</article>`).join('')}</section>`}).join('');return`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(trip.name||'完整行程')}</title><style>body{font-family:-apple-system,BlinkMacSystemFont,"PingFang TC",sans-serif;max-width:820px;margin:auto;padding:28px;color:#16302d;background:#f4f7f6}header,section{background:white;border:1px solid #dce7e4;border-radius:22px;padding:22px;margin-bottom:14px}h1{font-size:38px;letter-spacing:-.04em;margin:7px 0}.muted{color:#637875}.total{font-size:30px;color:#0f766e;font-weight:850;margin-top:16px}.line{display:flex;justify-content:space-between;gap:10px}.line span{font-size:11px;padding:4px 8px;border-radius:99px;background:#eef7f5}article{padding:14px 0;border-bottom:1px solid #e7efed;line-height:1.55}article:last-child{border:0}.money{font-weight:850;color:#a7640f}.tools{margin-bottom:14px}button{border:0;border-radius:12px;padding:10px 14px;background:#0f766e;color:white;font-weight:750}@media print{body{padding:0;background:white}.tools{display:none}header,section{break-inside:avoid}}</style></head><body><div class="tools"><button onclick="print()">列印／存成 PDF</button></div><header><div class="muted">完整旅行行程</div><h1>${escapeHtml(trip.name||'我的旅程')}</h1><div class="muted">${escapeHtml(trip.destination||'')}${trip.start?'・'+escapeHtml(trip.start)+' 至 '+escapeHtml(trip.end||'未定'):''}</div>${trip.notes?`<p>${escapeHtml(trip.notes)}</p>`:''}<div class="total">預算總額 ${yen(totalCost())}</div><div class="muted">製作時間：${new Date().toLocaleString('zh-HK')}</div></header>${sections||'<section>尚未加入行程</section>'}</body></html>`}
function downloadText(text,name,type){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([text],{type}));link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),2000)}
function downloadFinal(){if(!totalItems()){showToast('請先加入行程資料');return}downloadText(finalDocument(),(data.trip?.name||'完整旅行行程').replace(/[\\/:*?"<>|]/g,'-')+'.html','text/html;charset=utf-8')}
function printFinal(){const win=open('','_blank');win.document.write(finalDocument());win.document.close();setTimeout(()=>win.print(),350)}
function downloadBackup(){downloadText(JSON.stringify(data,null,2),'旅程私藏備份-'+new Date().toISOString().slice(0,10)+'.json','application/json')}
function restoreBackup(event){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{data=mergeData(data,normalize(JSON.parse(reader.result)));commit();showToast('備份已合併並同步')}catch{showToast('備份格式不正確')}};reader.readAsText(file);event.target.value=''}
function wipeAll(){if(!confirm('確定清除所有裝置共用的旅行資料？此操作不能復原。'))return;data=EMPTY();data.updatedAt=now();commit()}
$('#nav').addEventListener('click',event=>{const button=event.target.closest('button[data-page]');if(button)goPage(button.dataset.page)});
$('#addTabs').addEventListener('click',event=>{const button=event.target.closest('button[data-add]');if(button)setAddType(button.dataset.add)});
$('#listTabs').addEventListener('click',event=>{const button=event.target.closest('button[data-list]');if(button){currentListType=button.dataset.list;renderCategoryList()}});
$('#tripForm').addEventListener('submit',saveTrip);$('#addForm').addEventListener('submit',addEntry);$('#code').addEventListener('keydown',event=>{if(event.key==='Enter')unlock()});document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncNow(false)});window.addEventListener('pageshow',()=>{if(cryptoKey)syncNow(false)});
setAddType('plans');render();resumeSession();
